FROM ubuntu:18.04 as builder

RUN apt-get update -qy && apt-get -qy install \
        build-essential git nasm \
        libomxil-bellagio-dev

WORKDIR /root
RUN git clone --branch=n6.0 --single-branch --depth=1 https://github.com/FFmpeg/FFmpeg.git

WORKDIR /root/FFmpeg
RUN ./configure --arch=arm64 --target-os=linux --enable-gpl --enable-nonfree
RUN make -j$(nproc)
RUN make install

# FROM ubuntu:18.04
FROM node:20-buster-slim

RUN apt-get update \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /root
COPY --from=builder /usr/local/bin/ /usr/local/bin
COPY --from=builder /usr/local/lib/ /usr/local/lib
COPY --from=builder /usr/local/share/ffmpeg/ /usr/local/share/ffmpeg
COPY --from=builder /usr/local/share/man/ /usr/local/share/man

# CMD ["/bin/bash"]

# ENV LD_LIBRARY_PATH=/usr/local/lib

# COPY --from=ffmpeg / /

WORKDIR /app

COPY package\*.json /app/

RUN npm install

COPY src/ /app/src/

CMD node /app/src/index.js
